baseURL: https://www.ianunruh.com
languageCode: en-us
theme: PaperMod
title: Ian Unruh

params:
  homeInfoParams:
    Title: Random collection of tech learnings
    Content: DevOps, Kubernetes, OpenStack, Homelab

  socialIcons:
  - name: GitHub
    url: https://github.com/ianunruh
  - name: LinkedIn
    url: https://www.linkedin.com/in/ianunruh

  ShowShareButtons: true
  ShowReadingTime: true
  ShowCodeCopyButtons: true
  ShowPostNavLinks: true

  editPost:
    URL: https://github.com/ianunruh/blog/tree/main/content
    Text: Suggest Changes
    appendFilePath: true
